[package]
name = "tap_derive"
version = "0.1.0"
authors = ["Solal Jacob"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0" , features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.33"
